// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using workoutTracker.Domain.DatabaseContext;

#nullable disable

namespace workoutTracker.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325175216_AddTagTypeToTag")]
    partial class AddTagTypeToTag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VerifiedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("VerifiedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("VerifiedById");

                    b.HasIndex("VerifiedOn");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a7b067b-549e-4e6a-9d57-5f6735e4f88f"),
                            CreatedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            CreatedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 993, DateTimeKind.Unspecified).AddTicks(4313), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "A horizontal pressing movement performed with a deliberate pause at the chest. The pause eliminates the stretch-reflex, forcing the muscles to generate force from a dead stop and building strength at the most challenging point of the lift.",
                            Instructions = "Set up on the bench with eyes under the bar, retract your shoulder blades and arch your lower back slightly.\nUnrack the bar and position it over your lower chest with locked-out elbows.\nDescend with control, flaring the elbows slightly outward, until the bar touches your chest.\nPause for 1-2 full seconds — the bar must be motionless with no downward bounce.\nDrive the bar back up explosively, pressing your feet into the floor for leg drive.\nRe-rack only after achieving full lockout at the top.",
                            ModifiedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            ModifiedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 993, DateTimeKind.Unspecified).AddTicks(4313), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Bench Press (Paused)",
                            VerifiedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            VerifiedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 993, DateTimeKind.Unspecified).AddTicks(4313), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6bdc7a80-8bfa-4b8e-bbe4-0b5597279071"),
                            CreatedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            CreatedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 993, DateTimeKind.Unspecified).AddTicks(4313), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "A powerlifting squat variation where the bar rests lower on the rear deltoids rather than the traps. The lower bar position shifts the torso angle forward, recruiting the posterior chain more aggressively and allowing heavier loads to be moved.",
                            Instructions = "Position the bar across your rear deltoids, not your traps. Grip just outside shoulder width.\nStep back with two controlled steps, feet shoulder-width or slightly wider, toes turned out 15-30 degrees.\nTake a deep breath into your belly, brace your core hard, and push your knees out in the direction of your toes.\nDescend by hinging at the hips simultaneously with bending the knees, maintaining a forward torso lean.\nSquat until hip crease is at or below the top of the knee.\nDrive through the entire foot explosively, keeping the chest up and knees out on the ascent.",
                            ModifiedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            ModifiedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 993, DateTimeKind.Unspecified).AddTicks(4313), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Low Bar Squat",
                            VerifiedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            VerifiedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 993, DateTimeKind.Unspecified).AddTicks(4313), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            CreatedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            CreatedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 993, DateTimeKind.Unspecified).AddTicks(4313), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "The foundational hip-hinge movement for building total-body strength. The conventional stance targets the posterior chain — hamstrings, glutes, and spinal erectors — while also demanding significant upper back and grip strength to keep the bar controlled.",
                            Instructions = "Stand with feet hip-width apart, bar over mid-foot. Grip the bar just outside your legs, double-overhand or mixed grip.\nHinge at the hips to reach the bar, then drop the hips until your shins touch the bar without letting it roll forward.\nRetract your shoulder blades, lift your chest, and create tension in your lats by 'bending the bar around your legs'.\nTake a big breath, brace hard, then drive your feet into the floor while simultaneously pulling the slack out of the bar.\nKeep the bar in contact with your legs throughout the pull. Lock out by squeezing glutes and driving hips through at the top.\nReturn the bar to the floor with control by hinging at the hips first, then bending the knees once the bar passes them.",
                            ModifiedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            ModifiedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 993, DateTimeKind.Unspecified).AddTicks(4313), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Conventional Deadlift",
                            VerifiedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            VerifiedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 993, DateTimeKind.Unspecified).AddTicks(4313), new TimeSpan(0, 2, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.ExerciseTag", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("ExerciseId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ExerciseTag");

                    b.HasData(
                        new
                        {
                            ExerciseId = new Guid("4a7b067b-549e-4e6a-9d57-5f6735e4f88f"),
                            TagId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd68")
                        },
                        new
                        {
                            ExerciseId = new Guid("4a7b067b-549e-4e6a-9d57-5f6735e4f88f"),
                            TagId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6d")
                        },
                        new
                        {
                            ExerciseId = new Guid("4a7b067b-549e-4e6a-9d57-5f6735e4f88f"),
                            TagId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd64")
                        },
                        new
                        {
                            ExerciseId = new Guid("4a7b067b-549e-4e6a-9d57-5f6735e4f88f"),
                            TagId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f")
                        },
                        new
                        {
                            ExerciseId = new Guid("4a7b067b-549e-4e6a-9d57-5f6735e4f88f"),
                            TagId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f")
                        },
                        new
                        {
                            ExerciseId = new Guid("4a7b067b-549e-4e6a-9d57-5f6735e4f88f"),
                            TagId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd65")
                        },
                        new
                        {
                            ExerciseId = new Guid("4a7b067b-549e-4e6a-9d57-5f6735e4f88f"),
                            TagId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd63")
                        },
                        new
                        {
                            ExerciseId = new Guid("6bdc7a80-8bfa-4b8e-bbe4-0b5597279071"),
                            TagId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd69")
                        },
                        new
                        {
                            ExerciseId = new Guid("6bdc7a80-8bfa-4b8e-bbe4-0b5597279071"),
                            TagId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd65")
                        },
                        new
                        {
                            ExerciseId = new Guid("6bdc7a80-8bfa-4b8e-bbe4-0b5597279071"),
                            TagId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6e")
                        },
                        new
                        {
                            ExerciseId = new Guid("6bdc7a80-8bfa-4b8e-bbe4-0b5597279071"),
                            TagId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd64")
                        },
                        new
                        {
                            ExerciseId = new Guid("6bdc7a80-8bfa-4b8e-bbe4-0b5597279071"),
                            TagId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd50")
                        },
                        new
                        {
                            ExerciseId = new Guid("6bdc7a80-8bfa-4b8e-bbe4-0b5597279071"),
                            TagId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd61")
                        },
                        new
                        {
                            ExerciseId = new Guid("6bdc7a80-8bfa-4b8e-bbe4-0b5597279071"),
                            TagId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd51")
                        },
                        new
                        {
                            ExerciseId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            TagId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd66")
                        },
                        new
                        {
                            ExerciseId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            TagId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd65")
                        },
                        new
                        {
                            ExerciseId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            TagId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6e")
                        },
                        new
                        {
                            ExerciseId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            TagId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd64")
                        },
                        new
                        {
                            ExerciseId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            TagId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd50")
                        },
                        new
                        {
                            ExerciseId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            TagId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd61")
                        },
                        new
                        {
                            ExerciseId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            TagId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd51")
                        });
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Trial User",
                            RoleType = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "User",
                            RoleType = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Content Moderator",
                            RoleType = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Administrator",
                            RoleType = 3
                        });
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd50"),
                            Name = "Lower Body",
                            TagType = 1
                        },
                        new
                        {
                            Id = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f"),
                            Name = "Upper Body",
                            TagType = 1
                        },
                        new
                        {
                            Id = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd51"),
                            Name = "Core",
                            TagType = 1
                        },
                        new
                        {
                            Id = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f"),
                            Name = "Chest",
                            TagType = 2
                        },
                        new
                        {
                            Id = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd63"),
                            Name = "Shoulders",
                            TagType = 2
                        },
                        new
                        {
                            Id = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd61"),
                            Name = "Lower Back",
                            TagType = 2
                        },
                        new
                        {
                            Id = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd65"),
                            Name = "Upper Arms",
                            TagType = 2
                        },
                        new
                        {
                            Id = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd60"),
                            Name = "Forearms",
                            TagType = 2
                        },
                        new
                        {
                            Id = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd64"),
                            Name = "Thighs",
                            TagType = 2
                        },
                        new
                        {
                            Id = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd67"),
                            Name = "Abdominals",
                            TagType = 2
                        },
                        new
                        {
                            Id = new Guid("25553f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            Name = "Calves",
                            TagType = 2
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd68"),
                            Name = "Pectorals",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd64"),
                            Name = "Front Delts",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6b"),
                            Name = "Side Delts",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6a"),
                            Name = "Rear Delts",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6e"),
                            Name = "Spinal Erectors",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            Name = "Biceps",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6d"),
                            Name = "Triceps",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd62"),
                            Name = "Forearm Extensors",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd63"),
                            Name = "Forearm Flexors",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd69"),
                            Name = "Quadriceps",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd66"),
                            Name = "Hamstrings",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd65"),
                            Name = "Glutes",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd11"),
                            Name = "Adductors",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6f"),
                            Name = "Rectus Abdominis",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f"),
                            Name = "Obliques",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd60"),
                            Name = "Calves Soleus",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("752e3f65-ef2f-4646-b4d0-5f3e312bdd5f"),
                            Name = "Calves Gastroc",
                            TagType = 3
                        },
                        new
                        {
                            Id = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd67"),
                            Name = "Lats",
                            TagType = 3
                        });
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.TagChild", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("TEXT");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.ToTable("TagChild");

                    b.HasData(
                        new
                        {
                            ParentId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd50"),
                            ChildId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd64")
                        },
                        new
                        {
                            ParentId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd50"),
                            ChildId = new Guid("25553f65-ef2f-4646-b4d0-5f3e312bdd5e")
                        },
                        new
                        {
                            ParentId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f"),
                            ChildId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f")
                        },
                        new
                        {
                            ParentId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f"),
                            ChildId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd63")
                        },
                        new
                        {
                            ParentId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f"),
                            ChildId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd65")
                        },
                        new
                        {
                            ParentId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f"),
                            ChildId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd60")
                        },
                        new
                        {
                            ParentId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd51"),
                            ChildId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd61")
                        },
                        new
                        {
                            ParentId = new Guid("8b3e3f65-ef2f-4646-b4d0-5f3e312bdd51"),
                            ChildId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd67")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd68")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd63"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd64")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd63"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6b")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd63"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6a")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd61"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6e")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd65"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd65"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6d")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd60"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd62")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd60"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd63")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd64"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd69")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd64"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd66")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd64"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd65")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd64"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd11")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd67"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd6f")
                        },
                        new
                        {
                            ParentId = new Guid("2b3e3f65-ef2f-4646-b4d0-5f3e312bdd67"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd5f")
                        },
                        new
                        {
                            ParentId = new Guid("25553f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            ChildId = new Guid("7b3e3f65-ef2f-4646-b4d0-5f3e312bdd60")
                        },
                        new
                        {
                            ParentId = new Guid("25553f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            ChildId = new Guid("752e3f65-ef2f-4646-b4d0-5f3e312bdd5f")
                        });
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            CreatedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            CreatedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 998, DateTimeKind.Unspecified).AddTicks(1315), new TimeSpan(0, 2, 0, 0, 0)),
                            Email = "",
                            GoogleId = "",
                            ModifiedById = new Guid("5b3e3f65-ef2f-4646-b4d0-5f3e312bdd5e"),
                            ModifiedOn = new DateTimeOffset(new DateTime(2026, 3, 25, 19, 52, 15, 998, DateTimeKind.Unspecified).AddTicks(1315), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Automatic Process"
                        });
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.Exercise", b =>
                {
                    b.HasOne("workoutTracker.Domain.Models.Application.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("workoutTracker.Domain.Models.Application.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.ExerciseTag", b =>
                {
                    b.HasOne("workoutTracker.Domain.Models.Application.Exercise", "Exercise")
                        .WithMany("ExerciseTags")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("workoutTracker.Domain.Models.Application.Tag", "Tag")
                        .WithMany("ExerciseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.TagChild", b =>
                {
                    b.HasOne("workoutTracker.Domain.Models.Application.Tag", "Child")
                        .WithOne("TagParent")
                        .HasForeignKey("workoutTracker.Domain.Models.Application.TagChild", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("workoutTracker.Domain.Models.Application.Tag", "Parent")
                        .WithMany("TagChildren")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.UserRole", b =>
                {
                    b.HasOne("workoutTracker.Domain.Models.Application.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("workoutTracker.Domain.Models.Application.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.Exercise", b =>
                {
                    b.Navigation("ExerciseTags");
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.Tag", b =>
                {
                    b.Navigation("ExerciseTags");

                    b.Navigation("TagChildren");

                    b.Navigation("TagParent")
                        .IsRequired();
                });

            modelBuilder.Entity("workoutTracker.Domain.Models.Application.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
